#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705 - Deiteq
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    ############# Exists Checker
    - name: Pull Stored Data
      shell: "cat /pg/var/pgfork.project"
      register: basicproject

    ##################################################### SPLIT
    - name: Pull Stored Data
      shell: "cat /pg/var/pgfork.version"
      register: basicversion

    ############## Start Asking
    - pause:
        prompt: "\nWelcome to the PG Fork Interface!
                   \n\nYour GITHUB User-Name: {{basicproject.stdout}}
                   \nBranch-Release Link: {{basicversion.stdout}}
                   \n\n1 - EXIT the PG Fork
                   \n2 - Update Your GITHUB User-Name & Branch
                   \n3 - Download Current Forked Project
                   \n\nType a Selection Number"
      register: exit
      until: exit.user_input > "0" and exit.user_input < "4"
      retries: 99
      delay: 1

    - fail:
        msg: "User Opted NOT to CONTINUE! Aborting!"
      when: exit.user_input == "1"
    ############################## REGISTER PROJECT
    - pause:
        prompt: "\nWhat is Your GitHub UserName (Case Sensitive)?"
      register: project
      when: exit.user_input == "2"

    - name: Store User Name
      shell: "echo '{{project.user_input}}' > /pg/var/pgfork.project"
      when: exit.user_input == "2"
    ############################## REGISTER BRANCH
    - pause:
        prompt: "\nExample: Version-6 / mybranch / rclonefix\nPlease Update Your Branch-Release (Case Sensitive)"
      register: version
      when: exit.user_input == "2"

    - name: Store Project Link
      shell: "echo '{{version.user_input}}' > /pg/var/pgfork.version"
      when: exit.user_input == "2"
    ############################################# END
    - name: Reregister Project Link
      shell: "cat /pg/var/pgfork.project"
      register: projectfinal

    - name: Reregister Project Link
      shell: "cat /pg/var/pgfork.version"
      register: versionfinal

    - name: Clone Fork
      git:
        repo: "https://github.com/{{projectfinal.stdout}}/PGBlitz.com"
        dest: /opt/plexguide
        version: "{{versionfinal.stdout}}"
        force: yes

    - name: Note Fork Version
      shell: "echo 'Personal Fork' > /pg/var/pg.number"
