---
- hosts: localhost
  gather_facts: false
  tasks:

    - name: "Cloning PGBlitz"
      git:
        repo: "https://github.com/maxPGblitz/Install"
        dest: "/opt/pgstage"
        version: "raspi"
        force: yes
